name: compose-service-updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 0'
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:

  compose-service-updates:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: setup-git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: simple-compose-service-updates
        uses: sbe-arg/simple-compose-service-updates@v0.1.1
        with:
          default_branch: 'main'
        env:
          GH_TOKEN: ${{ github.token }}